// WARNING: This file has automatically been generated on Wed, 27 Mar 2019 18:55:16 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package kvmcapabilities

const (
	// ApiVersion as defined in linux/kvm.h:16
	ApiVersion = 12
	// TrcShift as defined in linux/kvm.h:20
	TrcShift = 16
	// TrcEntryexit as defined in linux/kvm.h:22
	TrcEntryexit = (1 << TrcShift)
	// TrcHandler as defined in linux/kvm.h:23
	TrcHandler = (1 << (TrcShift + 1))
	// TrcVmentry as defined in linux/kvm.h:25
	TrcVmentry = (TrcEntryexit + 0x01)
	// TrcVmexit as defined in linux/kvm.h:26
	TrcVmexit = (TrcEntryexit + 0x02)
	// TrcPageFault as defined in linux/kvm.h:27
	TrcPageFault = (TrcHandler + 0x01)
	// TrcHeadSize as defined in linux/kvm.h:29
	TrcHeadSize = 12
	// TrcCycleSize as defined in linux/kvm.h:30
	TrcCycleSize = 8
	// TrcExtraMax as defined in linux/kvm.h:31
	TrcExtraMax = 7
	// TrcInjVirq as defined in linux/kvm.h:33
	TrcInjVirq = (TrcHandler + 0x02)
	// TrcRedeliverEvt as defined in linux/kvm.h:34
	TrcRedeliverEvt = (TrcHandler + 0x03)
	// TrcPendIntr as defined in linux/kvm.h:35
	TrcPendIntr = (TrcHandler + 0x04)
	// TrcIoRead as defined in linux/kvm.h:36
	TrcIoRead = (TrcHandler + 0x05)
	// TrcIoWrite as defined in linux/kvm.h:37
	TrcIoWrite = (TrcHandler + 0x06)
	// TrcCrRead as defined in linux/kvm.h:38
	TrcCrRead = (TrcHandler + 0x07)
	// TrcCrWrite as defined in linux/kvm.h:39
	TrcCrWrite = (TrcHandler + 0x08)
	// TrcDrRead as defined in linux/kvm.h:40
	TrcDrRead = (TrcHandler + 0x09)
	// TrcDrWrite as defined in linux/kvm.h:41
	TrcDrWrite = (TrcHandler + 0x0A)
	// TrcMsrRead as defined in linux/kvm.h:42
	TrcMsrRead = (TrcHandler + 0x0B)
	// TrcMsrWrite as defined in linux/kvm.h:43
	TrcMsrWrite = (TrcHandler + 0x0C)
	// TrcCpuid as defined in linux/kvm.h:44
	TrcCpuid = (TrcHandler + 0x0D)
	// TrcIntr as defined in linux/kvm.h:45
	TrcIntr = (TrcHandler + 0x0E)
	// TrcNmi as defined in linux/kvm.h:46
	TrcNmi = (TrcHandler + 0x0F)
	// TrcVmmcall as defined in linux/kvm.h:47
	TrcVmmcall = (TrcHandler + 0x10)
	// TrcHlt as defined in linux/kvm.h:48
	TrcHlt = (TrcHandler + 0x11)
	// TrcClts as defined in linux/kvm.h:49
	TrcClts = (TrcHandler + 0x12)
	// TrcLmsw as defined in linux/kvm.h:50
	TrcLmsw = (TrcHandler + 0x13)
	// TrcApicAccess as defined in linux/kvm.h:51
	TrcApicAccess = (TrcHandler + 0x14)
	// TrcTdpFault as defined in linux/kvm.h:52
	TrcTdpFault = (TrcHandler + 0x15)
	// TrcGtlbWrite as defined in linux/kvm.h:53
	TrcGtlbWrite = (TrcHandler + 0x16)
	// TrcStlbWrite as defined in linux/kvm.h:54
	TrcStlbWrite = (TrcHandler + 0x17)
	// TrcStlbInval as defined in linux/kvm.h:55
	TrcStlbInval = (TrcHandler + 0x18)
	// TrcPpcInstr as defined in linux/kvm.h:56
	TrcPpcInstr = (TrcHandler + 0x19)
	// __DeprecatedMain0x07 as defined in linux/kvm.h:65
	__DeprecatedMain0x07 = 44551
	// __DeprecatedMain0x08 as defined in linux/kvm.h:66
	__DeprecatedMain0x08 = 44552
	// MemLogDirtyPages as defined in linux/kvm.h:110
	MemLogDirtyPages = (uint64(1) << 0)
	// MemReadonly as defined in linux/kvm.h:111
	MemReadonly = (uint64(1) << 1)
	// PitSpeakerDummy as defined in linux/kvm.h:149
	PitSpeakerDummy = 1
	// S390CmmaPeek as defined in linux/kvm.h:159
	S390CmmaPeek = (1 << 0)
	// ExitHypervSynic as defined in linux/kvm.h:189
	ExitHypervSynic = 1
	// ExitHypervHcall as defined in linux/kvm.h:190
	ExitHypervHcall = 2
	// S390GetSkeysNone as defined in linux/kvm.h:207
	S390GetSkeysNone = 1
	// S390SkeysMax as defined in linux/kvm.h:208
	S390SkeysMax = 1048576
	// ExitUnknown as defined in linux/kvm.h:210
	ExitUnknown = 0
	// ExitException as defined in linux/kvm.h:211
	ExitException = 1
	// ExitIo as defined in linux/kvm.h:212
	ExitIo = 2
	// ExitHypercall as defined in linux/kvm.h:213
	ExitHypercall = 3
	// ExitDebug as defined in linux/kvm.h:214
	ExitDebug = 4
	// ExitHlt as defined in linux/kvm.h:215
	ExitHlt = 5
	// ExitMmio as defined in linux/kvm.h:216
	ExitMmio = 6
	// ExitIrqWindowOpen as defined in linux/kvm.h:217
	ExitIrqWindowOpen = 7
	// ExitShutdown as defined in linux/kvm.h:218
	ExitShutdown = 8
	// ExitFailEntry as defined in linux/kvm.h:219
	ExitFailEntry = 9
	// ExitIntr as defined in linux/kvm.h:220
	ExitIntr = 10
	// ExitSetTpr as defined in linux/kvm.h:221
	ExitSetTpr = 11
	// ExitTprAccess as defined in linux/kvm.h:222
	ExitTprAccess = 12
	// ExitS390Sieic as defined in linux/kvm.h:223
	ExitS390Sieic = 13
	// ExitS390Reset as defined in linux/kvm.h:224
	ExitS390Reset = 14
	// ExitDcr as defined in linux/kvm.h:225
	ExitDcr = 15
	// ExitNmi as defined in linux/kvm.h:226
	ExitNmi = 16
	// ExitInternalError as defined in linux/kvm.h:227
	ExitInternalError = 17
	// ExitOsi as defined in linux/kvm.h:228
	ExitOsi = 18
	// ExitPaprHcall as defined in linux/kvm.h:229
	ExitPaprHcall = 19
	// ExitS390Ucontrol as defined in linux/kvm.h:230
	ExitS390Ucontrol = 20
	// ExitWatchdog as defined in linux/kvm.h:231
	ExitWatchdog = 21
	// ExitS390Tsch as defined in linux/kvm.h:232
	ExitS390Tsch = 22
	// ExitEpr as defined in linux/kvm.h:233
	ExitEpr = 23
	// ExitSystemEvent as defined in linux/kvm.h:234
	ExitSystemEvent = 24
	// ExitS390Stsi as defined in linux/kvm.h:235
	ExitS390Stsi = 25
	// ExitIoapicEoi as defined in linux/kvm.h:236
	ExitIoapicEoi = 26
	// ExitHyperv as defined in linux/kvm.h:237
	ExitHyperv = 27
	// InternalErrorEmulation as defined in linux/kvm.h:241
	InternalErrorEmulation = 1
	// InternalErrorSimulEx as defined in linux/kvm.h:243
	InternalErrorSimulEx = 2
	// InternalErrorDeliveryEv as defined in linux/kvm.h:245
	InternalErrorDeliveryEv = 3
	// ExitIoIn as defined in linux/kvm.h:285
	ExitIoIn = 0
	// ExitIoOut as defined in linux/kvm.h:286
	ExitIoOut = 1
	// S390ResetPor as defined in linux/kvm.h:325
	S390ResetPor = 1
	// S390ResetClear as defined in linux/kvm.h:326
	S390ResetClear = 2
	// S390ResetSubsystem as defined in linux/kvm.h:327
	S390ResetSubsystem = 4
	// S390ResetCpuInit as defined in linux/kvm.h:328
	S390ResetCpuInit = 8
	// S390ResetIpl as defined in linux/kvm.h:329
	S390ResetIpl = 16
	// SystemEventShutdown as defined in linux/kvm.h:374
	SystemEventShutdown = 1
	// SystemEventReset as defined in linux/kvm.h:375
	SystemEventReset = 2
	// SystemEventCrash as defined in linux/kvm.h:376
	SystemEventCrash = 3
	// S390MemopLogicalRead as defined in linux/kvm.h:473
	S390MemopLogicalRead = 0
	// S390MemopLogicalWrite as defined in linux/kvm.h:474
	S390MemopLogicalWrite = 1
	// S390MemopFCheckOnly as defined in linux/kvm.h:476
	S390MemopFCheckOnly = (uint64(1) << 0)
	// S390MemopFInjectException as defined in linux/kvm.h:477
	S390MemopFInjectException = (uint64(1) << 1)
	// MpStateRunnable as defined in linux/kvm.h:527
	MpStateRunnable = 0
	// MpStateUninitialized as defined in linux/kvm.h:528
	MpStateUninitialized = 1
	// MpStateInitReceived as defined in linux/kvm.h:529
	MpStateInitReceived = 2
	// MpStateHalted as defined in linux/kvm.h:530
	MpStateHalted = 3
	// MpStateSipiReceived as defined in linux/kvm.h:531
	MpStateSipiReceived = 4
	// MpStateStopped as defined in linux/kvm.h:532
	MpStateStopped = 5
	// MpStateCheckStop as defined in linux/kvm.h:533
	MpStateCheckStop = 6
	// MpStateOperating as defined in linux/kvm.h:534
	MpStateOperating = 7
	// MpStateLoad as defined in linux/kvm.h:535
	MpStateLoad = 8
	// S390SigpStop as defined in linux/kvm.h:547
	S390SigpStop = uint32(0xfffe0000)
	// S390ProgramInt as defined in linux/kvm.h:548
	S390ProgramInt = uint32(0xfffe0001)
	// S390SigpSetPrefix as defined in linux/kvm.h:549
	S390SigpSetPrefix = uint32(0xfffe0002)
	// S390Restart as defined in linux/kvm.h:550
	S390Restart = uint32(0xfffe0003)
	// S390IntPfaultInit as defined in linux/kvm.h:551
	S390IntPfaultInit = uint32(0xfffe0004)
	// S390IntPfaultDone as defined in linux/kvm.h:552
	S390IntPfaultDone = uint32(0xfffe0005)
	// S390Mchk as defined in linux/kvm.h:553
	S390Mchk = uint32(0xfffe1000)
	// S390IntClockComp as defined in linux/kvm.h:554
	S390IntClockComp = uint32(0xffff1004)
	// S390IntCpuTimer as defined in linux/kvm.h:555
	S390IntCpuTimer = uint32(0xffff1005)
	// S390IntVirtio as defined in linux/kvm.h:556
	S390IntVirtio = uint32(0xffff2603)
	// S390IntService as defined in linux/kvm.h:557
	S390IntService = uint32(0xffff2401)
	// S390IntEmergency as defined in linux/kvm.h:558
	S390IntEmergency = uint32(0xffff1201)
	// S390IntExternalCall as defined in linux/kvm.h:559
	S390IntExternalCall = uint32(0xffff1202)
	// S390IntIoMin as defined in linux/kvm.h:566
	S390IntIoMin = uint32(0x00000000)
	// S390IntIoMax as defined in linux/kvm.h:567
	S390IntIoMax = uint32(0xfffdffff)
	// S390IntIoAiMask as defined in linux/kvm.h:568
	S390IntIoAiMask = uint32(0x04000000)
	// S390PgmFlagsIlcValid as defined in linux/kvm.h:602
	S390PgmFlagsIlcValid = 0x01
	// S390PgmFlagsIlc0 as defined in linux/kvm.h:603
	S390PgmFlagsIlc0 = 0x02
	// S390PgmFlagsIlc1 as defined in linux/kvm.h:604
	S390PgmFlagsIlc1 = 0x04
	// S390PgmFlagsIlcMask as defined in linux/kvm.h:605
	S390PgmFlagsIlcMask = 0x06
	// S390PgmFlagsNoRewind as defined in linux/kvm.h:606
	S390PgmFlagsNoRewind = 0x08
	// S390StopFlagStoreStatus as defined in linux/kvm.h:623
	S390StopFlagStoreStatus = 0x01
	// GuestdbgEnable as defined in linux/kvm.h:661
	GuestdbgEnable = 0x00000001
	// GuestdbgSinglestep as defined in linux/kvm.h:662
	GuestdbgSinglestep = 0x00000002
	// IoeventfdFlagDatamatch as defined in linux/kvm.h:679
	IoeventfdFlagDatamatch = (1 << IoeventfdFlagNrDatamatch)
	// IoeventfdFlagPio as defined in linux/kvm.h:680
	IoeventfdFlagPio = (1 << IoeventfdFlagNrPio)
	// IoeventfdFlagDeassign as defined in linux/kvm.h:681
	IoeventfdFlagDeassign = (1 << IoeventfdFlagNrDeassign)
	// IoeventfdFlagVirtioCcwNotify as defined in linux/kvm.h:682
	IoeventfdFlagVirtioCcwNotify = (1 << IoeventfdFlagNrVirtioCcwNotify)
	// IoeventfdValidFlagMask as defined in linux/kvm.h:685
	IoeventfdValidFlagMask = ((1 << IoeventfdFlagNrMax) - 1)
	// X86DisableExitsMwait as defined in linux/kvm.h:696
	X86DisableExitsMwait = (1 << 0)
	// X86DisableExitsHlt as defined in linux/kvm.h:697
	X86DisableExitsHlt = (1 << 1)
	// X86DisableExitsPause as defined in linux/kvm.h:698
	X86DisableExitsPause = (1 << 2)
	// X86DisableValidExits as defined in linux/kvm.h:699
	X86DisableValidExits = (X86DisableExitsMwait | X86DisableExitsHlt | X86DisableExitsPause)
	// PpcPvinfoFlagsEvIdle as defined in linux/kvm.h:714
	PpcPvinfoFlagsEvIdle = (1 << 0)
	// PpcPageSizesMaxSz as defined in linux/kvm.h:724
	PpcPageSizesMaxSz = 8
	// PpcPageSizesReal as defined in linux/kvm.h:737
	PpcPageSizesReal = 0x00000001
	// Ppc1tSegments as defined in linux/kvm.h:738
	Ppc1tSegments = 0x00000002
	// PpcNoHash as defined in linux/kvm.h:739
	PpcNoHash = 0x00000004
	// VmS390Ucontrol as defined in linux/kvm.h:759
	VmS390Ucontrol = 1
	// VmPpcHv as defined in linux/kvm.h:762
	VmPpcHv = 1
	// VmPpcPr as defined in linux/kvm.h:763
	VmPpcPr = 2
	// VmMipsTe as defined in linux/kvm.h:766
	VmMipsTe = 0
	// VmMipsVz as defined in linux/kvm.h:767
	VmMipsVz = 1
	// S390SiePageOffset as defined in linux/kvm.h:769
	S390SiePageOffset = 1
	// VmTypeArmIpaSizeMask as defined in linux/kvm.h:777
	VmTypeArmIpaSizeMask = uint64(0xff)
	// GetApiVersion as defined in linux/kvm.h:783
	GetApiVersion = 44544
	// CreateVm as defined in linux/kvm.h:784
	CreateVm = 44545
	// S390EnableSie as defined in linux/kvm.h:787
	S390EnableSie = 44550
	// CheckExtension as defined in linux/kvm.h:792
	CheckExtension = 44547
	// GetVcpuMmapSize as defined in linux/kvm.h:796
	GetVcpuMmapSize = 44548
	// TraceEnable as defined in linux/kvm.h:798
	TraceEnable = __DeprecatedMainW0x06
	// TracePause as defined in linux/kvm.h:799
	TracePause = __DeprecatedMain0x07
	// TraceDisable as defined in linux/kvm.h:800
	TraceDisable = __DeprecatedMain0x08
	// CapIrqchip as defined in linux/kvm.h:807
	CapIrqchip = 0
	// CapHlt as defined in linux/kvm.h:808
	CapHlt = 1
	// CapMmuShadowCacheControl as defined in linux/kvm.h:809
	CapMmuShadowCacheControl = 2
	// CapUserMemory as defined in linux/kvm.h:810
	CapUserMemory = 3
	// CapSetTssAddr as defined in linux/kvm.h:811
	CapSetTssAddr = 4
	// CapVapic as defined in linux/kvm.h:812
	CapVapic = 6
	// CapExtCpuid as defined in linux/kvm.h:813
	CapExtCpuid = 7
	// CapClocksource as defined in linux/kvm.h:814
	CapClocksource = 8
	// CapNrVcpus as defined in linux/kvm.h:815
	CapNrVcpus = 9
	// CapNrMemslots as defined in linux/kvm.h:816
	CapNrMemslots = 10
	// CapPit as defined in linux/kvm.h:817
	CapPit = 11
	// CapNopIoDelay as defined in linux/kvm.h:818
	CapNopIoDelay = 12
	// CapPvMmu as defined in linux/kvm.h:819
	CapPvMmu = 13
	// CapMpState as defined in linux/kvm.h:820
	CapMpState = 14
	// CapCoalescedMmio as defined in linux/kvm.h:821
	CapCoalescedMmio = 15
	// CapSyncMmu as defined in linux/kvm.h:822
	CapSyncMmu = 16
	// CapIommu as defined in linux/kvm.h:823
	CapIommu = 18
	// CapDestroyMemoryRegionWorks as defined in linux/kvm.h:825
	CapDestroyMemoryRegionWorks = 21
	// CapUserNmi as defined in linux/kvm.h:826
	CapUserNmi = 22
	// CapSetGuestDebug as defined in linux/kvm.h:828
	CapSetGuestDebug = 23
	// CapReinjectControl as defined in linux/kvm.h:831
	CapReinjectControl = 24
	// CapIrqRouting as defined in linux/kvm.h:833
	CapIrqRouting = 25
	// CapIrqInjectStatus as defined in linux/kvm.h:834
	CapIrqInjectStatus = 26
	// CapAssignDevIrq as defined in linux/kvm.h:835
	CapAssignDevIrq = 29
	// CapJoinMemoryRegionsWorks as defined in linux/kvm.h:837
	CapJoinMemoryRegionsWorks = 30
	// CapMce as defined in linux/kvm.h:839
	CapMce = 31
	// CapIrqfd as defined in linux/kvm.h:841
	CapIrqfd = 32
	// CapPit2 as defined in linux/kvm.h:843
	CapPit2 = 33
	// CapSetBootCpuId as defined in linux/kvm.h:845
	CapSetBootCpuId = 34
	// CapPitState2 as defined in linux/kvm.h:847
	CapPitState2 = 35
	// CapIoeventfd as defined in linux/kvm.h:849
	CapIoeventfd = 36
	// CapSetIdentityMapAddr as defined in linux/kvm.h:850
	CapSetIdentityMapAddr = 37
	// CapXenHvm as defined in linux/kvm.h:852
	CapXenHvm = 38
	// CapAdjustClock as defined in linux/kvm.h:854
	CapAdjustClock = 39
	// CapInternalErrorData as defined in linux/kvm.h:855
	CapInternalErrorData = 40
	// CapVcpuEvents as defined in linux/kvm.h:857
	CapVcpuEvents = 41
	// CapS390Psw as defined in linux/kvm.h:859
	CapS390Psw = 42
	// CapPpcSegstate as defined in linux/kvm.h:860
	CapPpcSegstate = 43
	// CapHyperv as defined in linux/kvm.h:861
	CapHyperv = 44
	// CapHypervVapic as defined in linux/kvm.h:862
	CapHypervVapic = 45
	// CapHypervSpin as defined in linux/kvm.h:863
	CapHypervSpin = 46
	// CapPciSegment as defined in linux/kvm.h:864
	CapPciSegment = 47
	// CapPpcPairedSingles as defined in linux/kvm.h:865
	CapPpcPairedSingles = 48
	// CapIntrShadow as defined in linux/kvm.h:866
	CapIntrShadow = 49
	// CapDebugregs as defined in linux/kvm.h:868
	CapDebugregs = 50
	// CapX86RobustSinglestep as defined in linux/kvm.h:870
	CapX86RobustSinglestep = 51
	// CapPpcOsi as defined in linux/kvm.h:871
	CapPpcOsi = 52
	// CapPpcUnsetIrq as defined in linux/kvm.h:872
	CapPpcUnsetIrq = 53
	// CapEnableCap as defined in linux/kvm.h:873
	CapEnableCap = 54
	// CapXsave as defined in linux/kvm.h:875
	CapXsave = 55
	// CapXcrs as defined in linux/kvm.h:878
	CapXcrs = 56
	// CapPpcGetPvinfo as defined in linux/kvm.h:880
	CapPpcGetPvinfo = 57
	// CapPpcIrqLevel as defined in linux/kvm.h:881
	CapPpcIrqLevel = 58
	// CapAsyncPf as defined in linux/kvm.h:882
	CapAsyncPf = 59
	// CapTscControl as defined in linux/kvm.h:883
	CapTscControl = 60
	// CapGetTscKhz as defined in linux/kvm.h:884
	CapGetTscKhz = 61
	// CapPpcBookeSregs as defined in linux/kvm.h:885
	CapPpcBookeSregs = 62
	// CapSpaprTce as defined in linux/kvm.h:886
	CapSpaprTce = 63
	// CapPpcSmt as defined in linux/kvm.h:887
	CapPpcSmt = 64
	// CapPpcRma as defined in linux/kvm.h:888
	CapPpcRma = 65
	// CapMaxVcpus as defined in linux/kvm.h:889
	CapMaxVcpus = 66
	// CapPpcHior as defined in linux/kvm.h:890
	CapPpcHior = 67
	// CapPpcPapr as defined in linux/kvm.h:891
	CapPpcPapr = 68
	// CapSwTlb as defined in linux/kvm.h:892
	CapSwTlb = 69
	// CapOneReg as defined in linux/kvm.h:893
	CapOneReg = 70
	// CapS390Gmap as defined in linux/kvm.h:894
	CapS390Gmap = 71
	// CapTscDeadlineTimer as defined in linux/kvm.h:895
	CapTscDeadlineTimer = 72
	// CapS390Ucontrol as defined in linux/kvm.h:896
	CapS390Ucontrol = 73
	// CapSyncRegs as defined in linux/kvm.h:897
	CapSyncRegs = 74
	// CapPci23 as defined in linux/kvm.h:898
	CapPci23 = 75
	// CapKvmclockCtrl as defined in linux/kvm.h:899
	CapKvmclockCtrl = 76
	// CapSignalMsi as defined in linux/kvm.h:900
	CapSignalMsi = 77
	// CapPpcGetSmmuInfo as defined in linux/kvm.h:901
	CapPpcGetSmmuInfo = 78
	// CapS390Cow as defined in linux/kvm.h:902
	CapS390Cow = 79
	// CapPpcAllocHtab as defined in linux/kvm.h:903
	CapPpcAllocHtab = 80
	// CapReadonlyMem as defined in linux/kvm.h:904
	CapReadonlyMem = 81
	// CapIrqfdResample as defined in linux/kvm.h:905
	CapIrqfdResample = 82
	// CapPpcBookeWatchdog as defined in linux/kvm.h:906
	CapPpcBookeWatchdog = 83
	// CapPpcHtabFd as defined in linux/kvm.h:907
	CapPpcHtabFd = 84
	// CapS390CssSupport as defined in linux/kvm.h:908
	CapS390CssSupport = 85
	// CapPpcEpr as defined in linux/kvm.h:909
	CapPpcEpr = 86
	// CapArmPsci as defined in linux/kvm.h:910
	CapArmPsci = 87
	// CapArmSetDeviceAddr as defined in linux/kvm.h:911
	CapArmSetDeviceAddr = 88
	// CapDeviceCtrl as defined in linux/kvm.h:912
	CapDeviceCtrl = 89
	// CapIrqMpic as defined in linux/kvm.h:913
	CapIrqMpic = 90
	// CapPpcRtas as defined in linux/kvm.h:914
	CapPpcRtas = 91
	// CapIrqXics as defined in linux/kvm.h:915
	CapIrqXics = 92
	// CapArmEl132bit as defined in linux/kvm.h:916
	CapArmEl132bit = 93
	// CapSpaprMultitce as defined in linux/kvm.h:917
	CapSpaprMultitce = 94
	// CapExtEmulCpuid as defined in linux/kvm.h:918
	CapExtEmulCpuid = 95
	// CapHypervTime as defined in linux/kvm.h:919
	CapHypervTime = 96
	// CapIoapicPolarityIgnored as defined in linux/kvm.h:920
	CapIoapicPolarityIgnored = 97
	// CapEnableCapVm as defined in linux/kvm.h:921
	CapEnableCapVm = 98
	// CapS390Irqchip as defined in linux/kvm.h:922
	CapS390Irqchip = 99
	// CapIoeventfdNoLength as defined in linux/kvm.h:923
	CapIoeventfdNoLength = 100
	// CapVmAttributes as defined in linux/kvm.h:924
	CapVmAttributes = 101
	// CapArmPsci02 as defined in linux/kvm.h:925
	CapArmPsci02 = 102
	// CapPpcFixupHcall as defined in linux/kvm.h:926
	CapPpcFixupHcall = 103
	// CapPpcEnableHcall as defined in linux/kvm.h:927
	CapPpcEnableHcall = 104
	// CapCheckExtensionVm as defined in linux/kvm.h:928
	CapCheckExtensionVm = 105
	// CapS390UserSigp as defined in linux/kvm.h:929
	CapS390UserSigp = 106
	// CapS390VectorRegisters as defined in linux/kvm.h:930
	CapS390VectorRegisters = 107
	// CapS390MemOp as defined in linux/kvm.h:931
	CapS390MemOp = 108
	// CapS390UserStsi as defined in linux/kvm.h:932
	CapS390UserStsi = 109
	// CapS390Skeys as defined in linux/kvm.h:933
	CapS390Skeys = 110
	// CapMipsFpu as defined in linux/kvm.h:934
	CapMipsFpu = 111
	// CapMipsMsa as defined in linux/kvm.h:935
	CapMipsMsa = 112
	// CapS390InjectIrq as defined in linux/kvm.h:936
	CapS390InjectIrq = 113
	// CapS390IrqState as defined in linux/kvm.h:937
	CapS390IrqState = 114
	// CapPpcHwrng as defined in linux/kvm.h:938
	CapPpcHwrng = 115
	// CapDisableQuirks as defined in linux/kvm.h:939
	CapDisableQuirks = 116
	// CapX86Smm as defined in linux/kvm.h:940
	CapX86Smm = 117
	// CapMultiAddressSpace as defined in linux/kvm.h:941
	CapMultiAddressSpace = 118
	// CapGuestDebugHwBps as defined in linux/kvm.h:942
	CapGuestDebugHwBps = 119
	// CapGuestDebugHwWps as defined in linux/kvm.h:943
	CapGuestDebugHwWps = 120
	// CapSplitIrqchip as defined in linux/kvm.h:944
	CapSplitIrqchip = 121
	// CapIoeventfdAnyLength as defined in linux/kvm.h:945
	CapIoeventfdAnyLength = 122
	// CapHypervSynic as defined in linux/kvm.h:946
	CapHypervSynic = 123
	// CapS390Ri as defined in linux/kvm.h:947
	CapS390Ri = 124
	// CapSpaprTce64 as defined in linux/kvm.h:948
	CapSpaprTce64 = 125
	// CapArmPmuV3 as defined in linux/kvm.h:949
	CapArmPmuV3 = 126
	// CapVcpuAttributes as defined in linux/kvm.h:950
	CapVcpuAttributes = 127
	// CapMaxVcpuId as defined in linux/kvm.h:951
	CapMaxVcpuId = 128
	// CapX2apicApi as defined in linux/kvm.h:952
	CapX2apicApi = 129
	// CapS390UserInstr0 as defined in linux/kvm.h:953
	CapS390UserInstr0 = 130
	// CapMsiDevid as defined in linux/kvm.h:954
	CapMsiDevid = 131
	// CapPpcHtm as defined in linux/kvm.h:955
	CapPpcHtm = 132
	// CapSpaprResizeHpt as defined in linux/kvm.h:956
	CapSpaprResizeHpt = 133
	// CapPpcMmuRadix as defined in linux/kvm.h:957
	CapPpcMmuRadix = 134
	// CapPpcMmuHashV3 as defined in linux/kvm.h:958
	CapPpcMmuHashV3 = 135
	// CapImmediateExit as defined in linux/kvm.h:959
	CapImmediateExit = 136
	// CapMipsVz as defined in linux/kvm.h:960
	CapMipsVz = 137
	// CapMipsTe as defined in linux/kvm.h:961
	CapMipsTe = 138
	// CapMips64bit as defined in linux/kvm.h:962
	CapMips64bit = 139
	// CapS390Gs as defined in linux/kvm.h:963
	CapS390Gs = 140
	// CapS390Ais as defined in linux/kvm.h:964
	CapS390Ais = 141
	// CapSpaprTceVfio as defined in linux/kvm.h:965
	CapSpaprTceVfio = 142
	// CapX86DisableExits as defined in linux/kvm.h:966
	CapX86DisableExits = 143
	// CapArmUserIrq as defined in linux/kvm.h:967
	CapArmUserIrq = 144
	// CapS390CmmaMigration as defined in linux/kvm.h:968
	CapS390CmmaMigration = 145
	// CapPpcFwnmi as defined in linux/kvm.h:969
	CapPpcFwnmi = 146
	// CapPpcSmtPossible as defined in linux/kvm.h:970
	CapPpcSmtPossible = 147
	// CapHypervSynic2 as defined in linux/kvm.h:971
	CapHypervSynic2 = 148
	// CapHypervVpIndex as defined in linux/kvm.h:972
	CapHypervVpIndex = 149
	// CapS390AisMigration as defined in linux/kvm.h:973
	CapS390AisMigration = 150
	// CapPpcGetCpuChar as defined in linux/kvm.h:974
	CapPpcGetCpuChar = 151
	// CapS390Bpb as defined in linux/kvm.h:975
	CapS390Bpb = 152
	// CapGetMsrFeatures as defined in linux/kvm.h:976
	CapGetMsrFeatures = 153
	// CapHypervEventfd as defined in linux/kvm.h:977
	CapHypervEventfd = 154
	// CapHypervTlbflush as defined in linux/kvm.h:978
	CapHypervTlbflush = 155
	// CapS390Hpage1m as defined in linux/kvm.h:979
	CapS390Hpage1m = 156
	// CapNestedState as defined in linux/kvm.h:980
	CapNestedState = 157
	// CapArmInjectSerrorEsr as defined in linux/kvm.h:981
	CapArmInjectSerrorEsr = 158
	// CapMsrPlatformInfo as defined in linux/kvm.h:982
	CapMsrPlatformInfo = 159
	// CapPpcNestedHv as defined in linux/kvm.h:983
	CapPpcNestedHv = 160
	// CapHypervSendIpi as defined in linux/kvm.h:984
	CapHypervSendIpi = 161
	// CapCoalescedPio as defined in linux/kvm.h:985
	CapCoalescedPio = 162
	// CapHypervEnlightenedVmcs as defined in linux/kvm.h:986
	CapHypervEnlightenedVmcs = 163
	// CapExceptionPayload as defined in linux/kvm.h:987
	CapExceptionPayload = 164
	// CapArmVmIpaSize as defined in linux/kvm.h:988
	CapArmVmIpaSize = 165
	// CapManualDirtyLogProtect as defined in linux/kvm.h:989
	CapManualDirtyLogProtect = 166
	// CapHypervCpuid as defined in linux/kvm.h:990
	CapHypervCpuid = 167
	// IrqRoutingIrqchip as defined in linux/kvm.h:1023
	IrqRoutingIrqchip = 1
	// IrqRoutingMsi as defined in linux/kvm.h:1024
	IrqRoutingMsi = 2
	// IrqRoutingS390Adapter as defined in linux/kvm.h:1025
	IrqRoutingS390Adapter = 3
	// IrqRoutingHvSint as defined in linux/kvm.h:1026
	IrqRoutingHvSint = 4
	// IrqfdFlagDeassign as defined in linux/kvm.h:1075
	IrqfdFlagDeassign = (1 << 0)
	// IrqfdFlagResample as defined in linux/kvm.h:1083
	IrqfdFlagResample = (1 << 1)
	// ClockTscStable as defined in linux/kvm.h:1096
	ClockTscStable = 2
	// MmuFslBookeNohv as defined in linux/kvm.h:1106
	MmuFslBookeNohv = 0
	// MmuFslBookeHv as defined in linux/kvm.h:1107
	MmuFslBookeHv = 1
	// RegArchMask as defined in linux/kvm.h:1123
	RegArchMask = uint64(0xff00000000000000)
	// RegGeneric as defined in linux/kvm.h:1124
	RegGeneric = uint64(0x0000000000000000)
	// RegPpc as defined in linux/kvm.h:1130
	RegPpc = uint64(0x1000000000000000)
	// RegX86 as defined in linux/kvm.h:1131
	RegX86 = uint64(0x2000000000000000)
	// RegIa64 as defined in linux/kvm.h:1132
	RegIa64 = uint64(0x3000000000000000)
	// RegArm as defined in linux/kvm.h:1133
	RegArm = uint64(0x4000000000000000)
	// RegS390 as defined in linux/kvm.h:1134
	RegS390 = uint64(0x5000000000000000)
	// RegArm64 as defined in linux/kvm.h:1135
	RegArm64 = uint64(0x6000000000000000)
	// RegMips as defined in linux/kvm.h:1136
	RegMips = uint64(0x7000000000000000)
	// RegSizeShift as defined in linux/kvm.h:1138
	RegSizeShift = 52
	// RegSizeMask as defined in linux/kvm.h:1139
	RegSizeMask = uint64(0x00f0000000000000)
	// RegSizeU8 as defined in linux/kvm.h:1140
	RegSizeU8 = uint64(0x0000000000000000)
	// RegSizeU16 as defined in linux/kvm.h:1141
	RegSizeU16 = uint64(0x0010000000000000)
	// RegSizeU32 as defined in linux/kvm.h:1142
	RegSizeU32 = uint64(0x0020000000000000)
	// RegSizeU64 as defined in linux/kvm.h:1143
	RegSizeU64 = uint64(0x0030000000000000)
	// RegSizeU128 as defined in linux/kvm.h:1144
	RegSizeU128 = uint64(0x0040000000000000)
	// RegSizeU256 as defined in linux/kvm.h:1145
	RegSizeU256 = uint64(0x0050000000000000)
	// RegSizeU512 as defined in linux/kvm.h:1146
	RegSizeU512 = uint64(0x0060000000000000)
	// RegSizeU1024 as defined in linux/kvm.h:1147
	RegSizeU1024 = uint64(0x0070000000000000)
	// MsiValidDevid as defined in linux/kvm.h:1159
	MsiValidDevid = (uint32(1) << 0)
	// CreateDeviceTest as defined in linux/kvm.h:1177
	CreateDeviceTest = 1
	// DevVfioGroup as defined in linux/kvm.h:1192
	DevVfioGroup = 1
	// DevVfioGroupAdd as defined in linux/kvm.h:1193
	DevVfioGroupAdd = 1
	// DevVfioGroupDel as defined in linux/kvm.h:1194
	DevVfioGroupDel = 2
	// DevVfioGroupSetSpaprTce as defined in linux/kvm.h:1195
	DevVfioGroupSetSpaprTce = 3
	// CreateVcpu as defined in linux/kvm.h:1230
	CreateVcpu = 44609
	// SetNrMmuPages as defined in linux/kvm.h:1234
	SetNrMmuPages = 44612
	// GetNrMmuPages as defined in linux/kvm.h:1235
	GetNrMmuPages = 44613
	// SetTssAddr as defined in linux/kvm.h:1238
	SetTssAddr = 44615
	// CreateIrqchip as defined in linux/kvm.h:1252
	CreateIrqchip = 44640
	// CreatePit as defined in linux/kvm.h:1256
	CreatePit = 44644
	// AssignIrq as defined in linux/kvm.h:1268
	AssignIrq = __DeprecatedVmR0x70
	// ReinjectControl as defined in linux/kvm.h:1270
	ReinjectControl = 44657
	// SetBootCpuId as defined in linux/kvm.h:1280
	SetBootCpuId = 44664
	// SetTscKhz as defined in linux/kvm.h:1291
	SetTscKhz = 44706
	// GetTscKhz as defined in linux/kvm.h:1292
	GetTscKhz = 44707
	// Run as defined in linux/kvm.h:1334
	Run = 44672
	// DebugGuest as defined in linux/kvm.h:1342
	DebugGuest = __DeprecatedVcpuW0x87
	// S390StoreStatusNoaddr as defined in linux/kvm.h:1360
	S390StoreStatusNoaddr = (-uint64(1))
	// S390StoreStatusPrefixed as defined in linux/kvm.h:1361
	S390StoreStatusPrefixed = (-uint64(2))
	// S390InitialReset as defined in linux/kvm.h:1366
	S390InitialReset = 44695
	// Nmi as defined in linux/kvm.h:1370
	Nmi = 44698
	// KvmclockCtrl as defined in linux/kvm.h:1400
	KvmclockCtrl = 44717
	// Smi as defined in linux/kvm.h:1415
	Smi = 44727
	// DevAssignEnableIommu as defined in linux/kvm.h:1523
	DevAssignEnableIommu = (1 << 0)
	// DevAssignPci23 as defined in linux/kvm.h:1524
	DevAssignPci23 = (1 << 1)
	// DevAssignMaskIntx as defined in linux/kvm.h:1525
	DevAssignMaskIntx = (1 << 2)
	// DevIrqHostIntx as defined in linux/kvm.h:1538
	DevIrqHostIntx = (1 << 0)
	// DevIrqHostMsi as defined in linux/kvm.h:1539
	DevIrqHostMsi = (1 << 1)
	// DevIrqHostMsix as defined in linux/kvm.h:1540
	DevIrqHostMsix = (1 << 2)
	// DevIrqGuestIntx as defined in linux/kvm.h:1542
	DevIrqGuestIntx = (1 << 8)
	// DevIrqGuestMsi as defined in linux/kvm.h:1543
	DevIrqGuestMsi = (1 << 9)
	// DevIrqGuestMsix as defined in linux/kvm.h:1544
	DevIrqGuestMsix = (1 << 10)
	// DevIrqHostMask as defined in linux/kvm.h:1546
	DevIrqHostMask = 0x00ff
	// DevIrqGuestMask as defined in linux/kvm.h:1547
	DevIrqGuestMask = 0xff00
	// MaxMsixPerDev as defined in linux/kvm.h:1565
	MaxMsixPerDev = 256
	// X2apicApiUse32bitIds as defined in linux/kvm.h:1573
	X2apicApiUse32bitIds = (uint64(1) << 0)
	// X2apicApiDisableBroadcastQuirk as defined in linux/kvm.h:1574
	X2apicApiDisableBroadcastQuirk = (uint64(1) << 1)
	// ArmDevEl1Vtimer as defined in linux/kvm.h:1579
	ArmDevEl1Vtimer = (1 << 0)
	// ArmDevEl1Ptimer as defined in linux/kvm.h:1580
	ArmDevEl1Ptimer = (1 << 1)
	// ArmDevPmu as defined in linux/kvm.h:1581
	ArmDevPmu = (1 << 2)
	// HypervConnIdMask as defined in linux/kvm.h:1590
	HypervConnIdMask = 0x00ffffff
	// HypervEventfdDeassign as defined in linux/kvm.h:1591
	HypervEventfdDeassign = (1 << 0)
	// PioPageOffset as defined in asm/kvm.h:13
	PioPageOffset = 1
	// CoalescedMmioPageOffset as defined in asm/kvm.h:14
	CoalescedMmioPageOffset = 2
	// NrInterrupts as defined in asm/kvm.h:53
	NrInterrupts = 256
	// IoapicNumPins as defined in asm/kvm.h:83
	IoapicNumPins = 24
	// IrqchipPicMaster as defined in asm/kvm.h:108
	IrqchipPicMaster = 0
	// IrqchipPicSlave as defined in asm/kvm.h:109
	IrqchipPicSlave = 1
	// IrqchipIoapic as defined in asm/kvm.h:110
	IrqchipIoapic = 2
	// NrIrqchips as defined in asm/kvm.h:111
	NrIrqchips = 3
	// RunX86Smm as defined in asm/kvm.h:113
	RunX86Smm = (1 << 0)
	// ApicRegSize as defined in asm/kvm.h:126
	ApicRegSize = 0x400
	// CpuidFlagSignifcantIndex as defined in asm/kvm.h:223
	CpuidFlagSignifcantIndex = (1 << 0)
	// CpuidFlagStatefulFunc as defined in asm/kvm.h:224
	CpuidFlagStatefulFunc = (1 << 1)
	// CpuidFlagStateReadNext as defined in asm/kvm.h:225
	CpuidFlagStateReadNext = (1 << 2)
	// GuestdbgUseSwBp as defined in asm/kvm.h:259
	GuestdbgUseSwBp = 0x00010000
	// GuestdbgUseHwBp as defined in asm/kvm.h:260
	GuestdbgUseHwBp = 0x00020000
	// GuestdbgInjectDb as defined in asm/kvm.h:261
	GuestdbgInjectDb = 0x00040000
	// GuestdbgInjectBp as defined in asm/kvm.h:262
	GuestdbgInjectBp = 0x00080000
	// PitFlagsHpetLegacy as defined in asm/kvm.h:273
	PitFlagsHpetLegacy = 0x00000001
	// VcpueventValidNmiPending as defined in asm/kvm.h:287
	VcpueventValidNmiPending = 0x00000001
	// VcpueventValidSipiVector as defined in asm/kvm.h:288
	VcpueventValidSipiVector = 0x00000002
	// VcpueventValidShadow as defined in asm/kvm.h:289
	VcpueventValidShadow = 0x00000004
	// VcpueventValidSmm as defined in asm/kvm.h:290
	VcpueventValidSmm = 0x00000008
	// VcpueventValidPayload as defined in asm/kvm.h:291
	VcpueventValidPayload = 0x00000010
	// X86ShadowIntMovSs as defined in asm/kvm.h:294
	X86ShadowIntMovSs = 0x01
	// X86ShadowIntSti as defined in asm/kvm.h:295
	X86ShadowIntSti = 0x02
	// MaxXcrs as defined in asm/kvm.h:345
	MaxXcrs = 16
	// SyncX86Regs as defined in asm/kvm.h:360
	SyncX86Regs = (uint64(1) << 0)
	// SyncX86Sregs as defined in asm/kvm.h:361
	SyncX86Sregs = (uint64(1) << 1)
	// SyncX86Events as defined in asm/kvm.h:362
	SyncX86Events = (uint64(1) << 2)
	// SyncX86ValidFields as defined in asm/kvm.h:364
	SyncX86ValidFields = (SyncX86Regs | SyncX86Sregs | SyncX86Events)
	// X86QuirkLint0Reenabled as defined in asm/kvm.h:381
	X86QuirkLint0Reenabled = (1 << 0)
	// X86QuirkCdNwCleared as defined in asm/kvm.h:382
	X86QuirkCdNwCleared = (1 << 1)
	// X86QuirkLapicMmioHole as defined in asm/kvm.h:383
	X86QuirkLapicMmioHole = (1 << 2)
	// StateNestedGuestMode as defined in asm/kvm.h:385
	StateNestedGuestMode = 0x00000001
	// StateNestedRunPending as defined in asm/kvm.h:386
	StateNestedRunPending = 0x00000002
	// StateNestedEvmcs as defined in asm/kvm.h:387
	StateNestedEvmcs = 0x00000004
	// StateNestedSmmGuestMode as defined in asm/kvm.h:389
	StateNestedSmmGuestMode = 0x00000001
	// StateNestedSmmVmxon as defined in asm/kvm.h:390
	StateNestedSmmVmxon = 0x00000002
)

const (
	// IoeventfdFlagNrDatamatch as declared in linux/kvm.h:671
	IoeventfdFlagNrDatamatch = iota
	// IoeventfdFlagNrPio as declared in linux/kvm.h:672
	IoeventfdFlagNrPio = 1
	// IoeventfdFlagNrDeassign as declared in linux/kvm.h:673
	IoeventfdFlagNrDeassign = 2
	// IoeventfdFlagNrVirtioCcwNotify as declared in linux/kvm.h:674
	IoeventfdFlagNrVirtioCcwNotify = 3
	// IoeventfdFlagNrFastMmio as declared in linux/kvm.h:675
	IoeventfdFlagNrFastMmio = 4
	// IoeventfdFlagNrMax as declared in linux/kvm.h:676
	IoeventfdFlagNrMax = 5
)

// kvmDeviceType as declared in linux/kvm.h:1197
type kvmDeviceType int32

// kvmDeviceType enumeration from linux/kvm.h:1197
const (
	DevTypeFslMpic20  = 1
	DevTypeFslMpic42  = 2
	DevTypeXics       = 3
	DevTypeVfio       = 4
	DevTypeArmVgicV2  = 5
	DevTypeFlic       = 6
	DevTypeArmVgicV3  = 7
	DevTypeArmVgicIts = 8
	DevTypeMax        = 9
)

// sevCommandId as declared in linux/kvm.h:1444
type sevCommandId int32

// sevCommandId enumeration from linux/kvm.h:1444
const (
	SevInit              = iota
	SevEsInit            = 1
	SevLaunchStart       = 2
	SevLaunchUpdateData  = 3
	SevLaunchUpdateVmsa  = 4
	SevLaunchSecret      = 5
	SevLaunchMeasure     = 6
	SevLaunchFinish      = 7
	SevSendStart         = 8
	SevSendUpdateData    = 9
	SevSendUpdateVmsa    = 10
	SevSendFinish        = 11
	SevReceiveStart      = 12
	SevReceiveUpdateData = 13
	SevReceiveUpdateVmsa = 14
	SevReceiveFinish     = 15
	SevGuestStatus       = 16
	SevDbgDecrypt        = 17
	SevDbgEncrypt        = 18
	SevCertExport        = 19
	SevNrMax             = 20
)
